[package]
name = "jnix"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
keywords = ["ffi", "java", "jni"]
categories = ["external-ffi-bindings"]
repository = "https://github.com/mullvad/jnix"
edition = "2018"

[dependencies]
jni = "0.14"
once_cell = "1"
parking_lot = "0.9"
